name: Check de PR`s(Milestones, Labels, Assignes)
description: Verifica se um PR tem milestone, labels e assignees definidos.
author: carloshendvpm

inputs:
  github-token:
    description: Token de acesso ao GitHub
    required: true
    default: ${{ github.token }}
  custom-token:
    description: Token de acesso personalizado para comentar como outro usuário
    required: false
  comment-header:
    description: Cabeçalho personalizado para o comentário
    required: false
    default: '🤖 PR Check Bot'

runs:
  using: node20
  main: dist/index.js

branding:
  icon: check-circle
  color: green