export const messages = {
  pt: {
    title: 'Campos Obrigatórios Pendentes',
    intro: 'Este Pull Request está incompleto e precisa dos seguintes campos:',
    importance: 'Por que isso é importante?',
    milestoneImportance: 'Milestones ajudam a organizar entregas e acompanhar o progresso',
    assigneesImportance: 'Assignees garantem que alguém está responsável por este PR',
    labelsImportance: 'Labels categorizam e facilitam a filtragem dos PRs',
    howToResolve: 'Como resolver?',
    step1: 'Clique no botão **Edit** no topo deste PR',
    step2: 'Preencha os campos pendentes',
    step3: 'Clique em **Update pull request**',
    footer: 'Este comentário foi gerado automaticamente pelo sistema de verificação de PRs',
    milestoneMissing: '🔹 **Milestone**',
    assigneesMissing: '👤 **Assignees**',
    labelsMissing: '🏷️ **Labels**'
  },
  en: {
    title: 'Required Fields Missing',
    intro: 'This Pull Request is incomplete and requires the following fields:',
    importance: 'Why is this important?',
    milestoneImportance: 'Milestones help organize deliveries and track progress',
    assigneesImportance: 'Assignees ensure someone is responsible for this PR',
    labelsImportance: 'Labels categorize and facilitate PR filtering',
    howToResolve: 'How to resolve?',
    step1: 'Click the **Edit** button at the top of this PR',
    step2: 'Fill in the missing fields',
    step3: 'Click **Update pull request**',
    footer: 'This comment was automatically generated by the PR verification system',
    milestoneMissing: '🔹 **Milestone**',
    assigneesMissing: '👤 **Assignees**',
    labelsMissing: '🏷️ **Labels**'
  }
};