name: Verificar Campos do PR

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  push:
    branches:
      - main
      - master
      - develop

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Verificar PR
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          custom-token: ${{ secrets.CI_TOKEN }}
          language: 'en'